sonar.organization=lk562586fontys
sonar.projectKey=lk562586fontys
sonar.projectName=Game Tournament Frontend
sonar.exclusions=**/Dockerfile,**/Dockerfile.*,**/docker-compose.yml,**/docker-compose.yaml,**/api_key.env